apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: requestbin-deployment
spec:
  selector:
    matchLabels:
      app: requestbin
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: requestbin
    spec:
      containers:
      - name: requestbin
        image: crccheck/requestbin:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_URL
        - value: redis://81471092c56111e4.m.cnhza.kvstore.aliyuncs.com:6379/4
